# Site settings
title: shiba2046
description: Blog to record the stuff I always forget
author: shiba2046
  
lsi: true
safe: false
theme: minima

defaults:
  -
    scope:
      path: "_posts"
      type: "pages"
    values:
      layout: "post"